# -*- coding: utf-8 -*-
#################################################################################
# Author      : Acespritech Solutions Pvt. Ltd. (<www.acespritech.com>)
# Copyright(c): 2012-Present Acespritech Solutions Pvt. Ltd.
# All Rights Reserved.
#
# This program is copyright property of the author mentioned above.
# You can`t redistribute it and/or modify it.
#
#################################################################################
{
    'name': 'POS Restaurant with Responsive Design (Community)',
    'version': '1.0.4',
    'author': 'Acespritech Solutions Pvt. Ltd.',
    'summary': 'POS Restaurant with Responsive Design (Community)',
    'description': "POS Restaurant with Responsive Design (Community)",
    'category': 'Point Of Sale',
    'website': 'http://www.acespritech.com',
    'depends': ['base', 'point_of_sale', 'sale_management', 'barcodes', 'stock', 'purchase', 'bus',
                'hr_attendance', 'account', 'product_expiry', 'mrp', 'pos_restaurant', 'sale_stock', 'sale_management',
                'website'],
    'price': 390.00,
    'currency': 'EUR',
    'images': [
        'static/description/main_screenshot.png',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/reservation_data.xml',
        'data/product_expiry_scheduler.xml',
        'data/product_alert_email_template.xml',
        'data/pos_cache_data.xml',
        'data/account_financial_report_data.xml',
        'data/customer_schedular.xml',
        'views/res_config_setting_view.xml',
        'views/flexibite.xml',
        'views/res_config_settings.xml',
        'views/generate_product_barcode_view.xml',
        'views/point_of_sale.xml',
        'views/pos_config.xml',
        'views/res_config_settings.xml',
        'views/product_view.xml',
        'views/product_brand_view.xml',
        'views/res_company_view.xml',
        'views/loyalty_config_view.xml',
        'views/loyalty_view.xml',
        'views/res_partner_view.xml',
        'views/gift_card.xml',
        'views/voucher_view.xml',
        'views/voucher_code_sequence.xml',
        'views/res_users_view.xml',
        'views/pos_payment_method_view.xml',
        'views/pos_sales_report_template.xml',
        'views/pos_sales_report_pdf_template.xml',
        'views/sales_details_pdf_template.xml',
        'views/sales_details_template.xml',
        'views/front_sales_report_pdf_template.xml',
        'views/front_sales_thermal_report_template.xml',
        'views/front_inventory_session_pdf_report_template.xml',
        'views/front_inventory_session_thermal_report_template.xml',
        'views/front_inventory_location_pdf_report_template.xml',
        'views/front_inventory_location_thermal_report_template.xml',
        'views/pos_report.xml',
        'reports.xml',
        'views/pos_promotion_view.xml',
        'views/pos_store_view.xml',
        'views/stock_production_lot_view.xml',
        'views/wallet_management_view.xml',
        'views/cash_inout_menu.xml',
        'views/stock.xml',
        'views/customer_display.xml',
        'views/dashboard.xml',
        'views/pos_cache_views.xml',
        'views/delivery_order_screen.xml',
        'wizard/set_product_valid_days.xml',
        'wizard/tax_report_wiz_view.xml',
        'wizard/aged_payble_view.xml',
        'wizard/trial_balance_wiz_view.xml',
        'wizard/aged_receivable_view.xml',
        'wizard/account_report_partner_ledger_view.xml',
        'wizard/profit_and_loss.xml',
        'wizard/balance_sheet.xml',
        'report/account_report.xml',
        'report/report_financial.xml',
        'wizard/general_ledger_wiz_view.xml',
        'views/tax_report_template.xml',
        'views/trial_balance_template.xml',
        'views/aged_payble_template.xml',
        'views/aged_receivable_template.xml',
        'views/partner_ledger_template.xml',
        'views/account_pdf_reports.xml',
        'views/general_ledger_template.xml',
        'report/non_moving_product_report.xml',
        'views/res_config_settings.xml',
        'wizard/non_moving_stock.xml',
        'data/send_mail.xml',
        'report/grp_category_product_expiry_report_template.xml',
        'wizard/product_expiry_report_wizard_view.xml',
        'views/product_expiry_report_view.xml',
        'views/mrp_bom_view.xml',
        'views/wallet_view.xml',
    ],
    'post_init_hook': 'post_init',
    'qweb': ['static/src/xml/*.xml'],
    'installable': True,
    'application': True,
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
